language: java
on: [push]

jobs:
 check-bats-version:
  runs-on: ubuntu-latest
  steps:
   - run: mvn test-compile -pl jung-algorithms -am
   - run: mvn -pl jung-algorithms test -Dtest=edu.uci.ics.jung.algorithms.shortestpath.TestMinimumSpanningTree#testDAG

